server.port=8085

spring.application.name=api-gateway-new



eureka.client.service-url.defaultZone = http://localhost:8081/eureka

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true



